# This compose file can be useful for development purposes.
# It starts Grafana with this plugin installed (you still need to build it first).
# It also starts a preconfigured example Yamcs server.
#
# Usage:
# - docker-compose up
# - Navigate to Grafana (localhost:3000), and add a new datasource.
# - Select 'Yamcs', it should appear in the list of choices.
# - With Server Access, use http://yamcs:8090 as the URL.
services:
  grafana:
    user: root
    container_name: 'yamcs-yamcs-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/yamcs-yamcs-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/yamcs-yamcs-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.yamcs-yamcs-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: yamcs-yamcs-datasource

  yamcs:
    image: yamcs/example-simulation:latest
    ports:
      - '8090:8090'
