# This compose file can be useful for development purposes.
# It starts Grafana with this plugin installed (you still need to build it first).
# It also starts a preconfigured example Yamcs server.
#
# Usage:
# - docker-compose up
# - Navigate to Grafana (localhost:3000), and add a new datasource.
# - Select 'Yamcs', it should appear in the list of choices.
# - With Server Access, use http://yamcs:8090 as the URL.
version: '3.7'
services:
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - '3000:3000'
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=yamcs-yamcs-datasource
    volumes:
      - .:/var/lib/grafana/plugins/yamcs-yamcs-datasource

  yamcs:
    image: yamcs/example-simulation:latest
    ports:
      - "8090:8090"
